version: "3.8"

services:
    app:
        image: laravelphp/php-fpm
        container_name: loan-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - loan-network

    webserver:
        image: nginx:alpine
        container_name: loan-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - loan-network

    db:
        image: mysql:8.0
        container_name: loan-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: loan_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - loan-network

networks:
    loan-network:
        driver: bridge

volumes:
    dbdata:
